### PR TITLE
Perf improvement

### PR DESCRIPTION
**Pull request by alexfedoseev**
```reason
// Current
Cn.make([x1, x2, x3->ifTrue(cond)])

// Next
CnNext.(x1 + x2 + x3->on(cond))
```

Motivation: the proposed API is ~1.6x faster.

#### Benchmarks
```shell
Cn API x 685,194 ops/sec ±0.75% (91 runs sampled)
CnNext API x 1,153,043 ops/sec ±0.78% (92 runs sampled)
The fastest: [ 'CnNext API' ]
```

#### API
I'm open to suggestions on naming and all.

```reason
// Interface
let (+): (string, string) => string;
let none: string;
let on: (string, bool) => string;
let onSome: (string, option('a)) => string;
let mapSome: (option('a), 'a => string) => string;
let take: option(string) => string;
let onOk: (string, result('a, 'b)) => string;
let mapOk: (result('a, 'b), 'a => string) => string;
let onErr: (string, result('a, 'b)) => string;
let mapErr: (result('a, 'b), 'b => string) => string;

// Changes
Cn.make -> Cn.(+)
Cn.ifTrue -> Cn.on
Cn.ifSome -> Cn.onSome
Cn.unpack -> Cn.take

// New
Cn.none
Cn.onOk
Cn.mapOk
Cn.onErr
Cn.mapErr
```

#### Release plan
Keep the new and the old APIs within a single `Cn` module (in the current state of PR the new implementation is in the `CnNext` module but it's temporary).
Add `[@deprecated]` annotation to the updated functions.
In the next major, remove deprecated functions.

#### Notes
The new API triggers warning `44`. I'm not sure how critical this is for users. I usually disable this one.

### CODE REVIEW

**Comment by johnridesabike** [comment]
Overall this looks really nice, but I have a few concerns and suggestions:

I don’t like that users have to disable warning 44, especially since BuckleScript enables the warning by default.

I think there should be a regular function equivalent to `+`, something like `add` or `append`.

Aside from triggering warning 44, I’m unsure if `+` is the best choice anyway, since we’re not “adding” numbers, we’re concatenating strings. I believe [Bastet](https://github.com/Risto-Stevcev/bastet/) uses `<:>` for this.

My proposal:
```diff 
// Interface
+ let append: (string, string) => string;
+ let (<:>): (string, string) => string;
let (+): (string, string) => string;
```
These can all point to the same function.

Aside from that, this new API looks great!

**Comment by johnridesabike** [comment]
Another observation:

I notice that the old list API uses `String.concat` with `Belt.List.keep`. We can significantly speed up the list function by rewriting it:

```reason
let make = cns => {
  let rec aux = (acc, l) =>
    switch (l) {
    | [] => acc
    | [a, ...rest] when a == "" => aux(acc, rest)
    | [a, ...rest] => aux(a ++ " " ++ acc, rest)
    };
  aux("", cns);
}
```

Old list API `make`:
```
Cn List API x 798,530 ops/sec ±0.35% (89 runs sampled)
```

New list API `make`:
```
Cn List API x 2,076,885 ops/sec ±0.49% (91 runs sampled)
```

~2.6 times faster.

**Comment by alexfedoseev** [comment]
@johnridesabike Great catch! It actually is faster than submitted `(+)` API and I figured why. Here is the updated benchmarks:

```shell
Cn List API x 689,929 ops/sec ±0.68% (92 runs sampled)
Cn List Rec API x 1,688,069 ops/sec ±1.05% (87 runs sampled)
Cn (+) API: interpolation x 1,169,732 ops/sec ±0.90% (91 runs sampled)
Cn (+) API: concatenation x 4,060,955 ops/sec ±0.66% (93 runs sampled)
The fastest: [ 'Cn (+) API: concatination' ]
```  

`Cn (+) API: interpolation` is the current implementation:

```reason
let (+) = (x1, x2) =>
  switch (x1, x2) {
  | ("", "") => none
  | (x1, "") => x1
  | ("", x2) => x2
  | (x1, x2) => {j|$(x1) $(x2)|j}
  };
```

Which compiles to 

```js
function $plus(x1, x2) {
  if (x1 === "" && x2 === "") {
    return none;
  }
  if (x2 === "") {
    return x1;
  } else if (x1 === "") {
    return x2;
  } else {
    return "" + (String(x1) + (" " + (String(x2) + "")));
  }
}
```

But if I replace string interpolation (which allocates 2 new `String`s) with simple concatenation, then ✨

```reason
let (+) = (x1, x2) =>
  switch (x1, x2) {
  | ("", "") => none
  | (x1, "") => x1
  | ("", x2) => x2
  | (x1, x2) => x1 ++ " " ++ x2
  };
```

```js
function $plus(x1, x2) {
  if (x1 === "" && x2 === "") {
    return none;
  }
  if (x2 === "") {
    return x1;
  } else if (x1 === "") {
    return x2;
  } else {
    return x1 + (" " + x2);
  }
}
```

String interpolation in BuckleScript is in a bad state lol

Anyway, the total improvement is ~5.9x. I feel bad for not spotting it earlier.

**Comment by yawaramin** [comment]
> I don’t like that users have to disable warning 44, especially since BuckleScript enables the warning by default.

FWIW, I feel it should be turned off but a lot of other warnings/errors should be turned on by default in BuckleScript projects. See https://github.com/BuckleScript/bucklescript/issues/3471

**Pull request merged**
